# ~/.streamlit/config.toml

[ui]
hideTopBar = true

[server]
runOnSave = false

[theme]
primaryColor="#c70039"
backgroundColor="#f9f9f9"
secondaryBackgroundColor="#ECECEC"
textColor="#000000"

[mapbox]
token = "your-mapbox-token"

[customComponent]
# Path to a folder containing JavaScript files for custom components
componentJsPath = "/path/to/components"
# .streamlit/config.toml

