# ~/.streamlit/config.toml

[server]
runOnSave = false

[theme]
base = "dark"
primaryColor = "#C70039"
backgroundColor = "#E5E4E2"
secondaryBackgroundColor = "#D3D3D3"
textColor = "#000000"
font = "sans serif"


[mapbox]
token = "your-mapbox-token"


[customComponent]
# Path to a folder containing JavaScript files for custom components
componentJsPath = "/path/to/components"

