[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "📄"

[[pages]]
name = "Cool apps"
icon = ":pig:"
is_section = true

[[pages]]
path = "01_Shipping_Report.py"
name = "Shipping Report"
icon = ":material/history:"

[[pages]]
path = "02_Supply_Chain.py"
name = "O2_Supply_Chain.py"
icon = "📖"

[[pages]]
name = "Other apps"
icon = ":horse:"
is_section = true

[[pages]]
path = "03_Marketing.py"

[[pages]]
path = "04_Sales.py"
name = "Sales"
icon = "🧰"