[[pages]]
path = "streamlit_app.py"
name = "Home"

[[pages]]
name = "Sales"
is_section = true

[[pages]]
path = "./pages/01_Shipping_Report.py"
name = "Shipping Report"
icon = ":material/history:"

[[pages]]
path = "./pages/02_Supply_Chain.py"
name = "O2_Supply_Chain.py"
icon = "📖"

[[pages]]
name = "Operations"
icon = ":horse:"
is_section = true

[[pages]]
path = "./pages/03_Marketing.py"

[[pages]]
path = "./pages/04_Sales.py"
name = "Sales"
icon = "🧰"